export const types = {
    SET_DATA:  'SET_DATA',
    GET_DATA:  'GET_DATA',
    SET_MATCH: 'SET_MATCH',
    GET_MATCH: 'GET_MATCH',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    GET_NOTIFICATION: 'GET_NOTIFICATION'
};
